### ISSUE TITLE
The link is not working.Please update this Link...

### ISSUE THREAD

**Issue by Kalyan8121** [ThilakReddyy/JNTUH_RESULTS#3]
Most of the Final year Students Need this to calculate Overall CGPA..

**Comment by Kalyan8121** [comment]
> 
> Most of the Final year Students Need this to calculate Overall CGPA..

**Comment by ThilakReddyy** [comment]
Alternate link : jntuhresult.herokuapp.com

**Comment by Kalyan8121** [comment]
> Alternate link : jntuhresult.herokuapp.com

Thanks 😊👍🏻
